### ISSUE TITLE
@-prefixed hash' key (aliases): valid YAML?

### ISSUE THREAD

**Issue by drzraf** [wp-cli/config-command#58]
I try to dynamically generate/edit `~/.wp-cli/config.yml`  and need to parse this file.
I expect it to be valid YAML but it seems it's not:

$ `cat ~/.wp-cli/config.yml`
```yaml
disabled_commands:
  - db drop
@ae:
  path: /web/wp
```

$ `python3 -c "import os,yaml; x = yaml.load(open(os.path.expanduser('~/.wp-cli/config.yml'), 'r').read());"`
```
yaml.scanner.ScannerError: while scanning for the next token
found character '@' that cannot start any token
  in "<unicode string>", line 3, column 1:
    @ae:
    ^
```

Where would YAML specifically allow the "@" character as a dictionary key?
Any documentation/clarification on this?

**Comment by drzraf** [comment]
Another artefact:
```yaml
'@ae':
    path: /web/wp
disabled_commands:
-   db drop
```
(notice the space being between dash and value rather than before the dash)

is correct YAML (https://github.com/ansible/ansible/issues/28427#issuecomment-323820186)
but fails with `PHP Warning:  in_array() expects parameter 2 to be array, string given in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php on line 541
`
